spring:
  application:
    name: movie
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:movie}
    username: ${DB_USERNAME:movie}
    password: ${DB_PASSWORD:password}